stages:

  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
    outs: 
      - data/processed
 

  data_transformation:
      cmd: python src/components/data_transformation.py
      deps:
        - data/raw
        - data/processed
        - configs/data_constants_config.py 
        - src/components/data_transformation.py
      outs:
        - artifacts
     

  experiment_splitter:
      cmd: python src/components/experiment_splitter.py
      deps: 
        - data/processed
        - artifacts
        - src/components/experiment_splitter.py
      

  ml_model_trainer:
      cmd: python src/pipeline/xgboost_training.py
      deps:
        - artifacts
        - configs/data_constants_config.py
        - src/pipeline/xgboost_training.py
      
  
    
